refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  infofile:
    kind: rolling_file
    path: "log/info.log"
    append: true
    encoder:
      pattern: "{d} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 mb
      roller:
        kind: fixed_window
        base: 1
        count: 7
        pattern: log/info-{}.log
root:
  level: info
  appenders:
    - infofile
